# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: My vi Site
site_url: https://maroph.github.io/ex-vi
site_description: Dedicated to Bill Joy's vi Implementation
site_author: Manfred Rosenboom (maroph)
#
repo_name: maroph/ex-vi
repo_url: https://github.com/maroph/ex-vi
edit_uri: edit/main/docs
#
# MkDocs Theme: Material for MkDocs
# https://squidfunk.github.io/mkdocs-material/
theme:
    name: material
    palette:
        scheme: default
        accent: indigo
    font: false
    language: en
    direction: ltr
    favicon: assets/Vi_logo.ico
    features:
        - header.autohide
        - content.action.edit
        - content.action.view
        - content.code.copy
        - navigation.footer
        - navigation.indexes
        - navigation.instant
        - navigation.tracking
        - navigation.tabs
        - navigation.tabs.sticky
        - search.suggest
        - search.highlight
    icon:
        repo: fontawesome/brands/github
        edit: material/pencil 
        view: material/eye

nav:
    - Home: index.md
    - Documentation: documentation.md
    - Software:
      - heirloom-ex-vi: software/heirloom-ex-vi.md
      - ex-vi: software/ex-vi.md
      - Ex 1.1: software/ex-1.1.md
      - Termcap: software/termcap.md
    - Info:
        - About: info/about.md
        - GDPR/DSGVO: info/gdpr.md
        - License: info/license.md
        - Resources: info/resources.md

not_in_nav:
    /software/*.1.md

docs_dir: docs
site_dir: site

use_directory_urls: false
strict: true

copyright: Copyright (c) 2023 <a href="https://github.com/maroph">Manfred Rosenboom</a>

markdown_extensions:
    - attr_list
    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - tables

plugins:
    - git-revision-date-localized:
          enable_creation_date: false
          type: iso_datetime
    - search:
        lang: en

